targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          create_to_json: false
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.g.dart'
